from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.4.1")

# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
#container: "docker://continuumio/miniconda3"



##### load rules #####
include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/trim.smk"
include: "rules/qc.smk"
include: "rules/align.smk"
include: "rules/diffexp.smk"
include: "rules/countmatrix.smk"
include: "rules/genotyping.smk"


##### target rules #####

rule all:
    input:
        "results/pca.pdf",
        get_final_output(),
        "results/counts/all_tpm.tsv",
        "results/qc/multiqc_report.html",
