# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
#container: "docker://continuumio/miniconda3"

#workdir: "/cluster/projects/mcgahalab/data/mcgahalab/wither_mcgaha_ram/snakemake_workflow/"
#workdir: "/cluster/home/selghamr/workflows/intialize/rnaseq-star"
#workdir:"/cluster/projects/cesconlab/Projects/TGL10_Oct2021/rnaseq-star"
workdir:"/cluster/projects/cesconlab/Projects/TFRI_TNBC/UHN_PDX_PDO_Cescon/rnaseq/20200824/rnaseq-star"


##### load rules #####
include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/trim.smk"
include: "rules/qc.smk"
include: "rules/align.smk"
include: "rules/diffexp.smk"
include: "rules/countmatrix.smk"
include: "rules/genotyping.smk"


##### target rules #####

rule all:
    input:
        "results/pca.pdf",
        get_final_output(),
        "results/counts/all_tpm.tsv",
        "results/qc/multiqc_report.html",
