# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: config/units.tsv

#define paths for available resources or to generate them (basically the reference genome)
paths:
  base_ref: "/shared/resources/references"
  base_out: ""
  tmp: ""

ref:
  # Ensembl species name [homo_sapiens, or mus_musculus]
  species: "homo_sapiens"
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 100
  # Genome build
  build: "GRCh38"

ref_index:
  bwa-index: "ref/genomes/human/GRCh38/BWAIndex"
  genome: "ref/genomes/human/GRCh38/genome.fa"
  # This reference file is made from rsem-prepare-reference, it will generate the reference.seq is not found
  rsem: "ref/RSEM/GRCh38/"

trimming:
  # Should not be trimming RNAseq data, especially for STAR2, I haven't tested True
  activate: False

mergeReads:
  # Non-functional, keep to False
  activate: False

pca:
  activate: True
  labels:
    # columns of sample sheet to use for PCA
    - condition

genotyping:
  target: "ref/dbsnp/GRCh38/b151/dbSNP_GRCh38p7_b151_common.bed"
  # Currently non-functional, does not use these parameters at all
  min_n: 2

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    treated-vs-untreated:
      - treated
      - untreated
  model: ~condition

params:
  cutadapt-pe: ""
  cutadapt-se: ""

rsem:
  refpath: ""
gsea:
  # Only include genes with an expression above this value for GSEA (set to 0)
  min_base_mean: 50
  # Report significant GSEA/over-representation for this p-value or lower
  max_p: 0.05

star:
  star-genome: "/shared/resources/references/star_genome"
  gtf: "/cluster/projects/cesconlab/References/STAR/GRCh38/GTF/genome.gtf"
  base_out: ""
  # Extra params added for STARv2
  params: "--outSAMtype BAM SortedByCoordinate --readFilesCommand zcat --alignIntronMin 30 --alignIntronMax 1200000 --outSAMunmapped Within"
  extra: "" #parametrs to activate additional features of STAR, such as reads counting and the chimeric alignment. Some examples below
  # extra: "--quantMode GeneCounts TranscriptomeSAM --outFilterIntronMotifs RemoveNoncanonical --chimSegmentMin 10 --chimOutType Junctions"
